site_name: Asperato developers
theme_dir: customtheme
docs_dir: docsrc
repo_url: https://github.com/Asperato/docs
pages:
- 'index.md'
- "Overview": 'overview.md'
- "Asperato ONE": 'sf.md'
- "Templates": 'templates.md'
